cicd_pipeline.yml

diff --git a/.github/workflows/cicd_pipeline.yml b/.github/workflows/cicd_pipeline.yml
--- a/.github/workflows/cicd_pipeline.yml
+++ b/.github/workflows/cicd_pipeline.yml
@@ -43,19 +43,17 @@ jobs:
 
     - name: Set up SSH known_hosts and private key
       run: |
-        # Ensure the SSH directory exists
         mkdir -p ~/.ssh
         chmod 700 ~/.ssh
-
-        # Retrieve the EC2 instance's public IP and add it to known_hosts
+        EC2_PUBLIC_IP=$(terraform output -raw instance_public_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
+        if [ -z "$EC2_PUBLIC_IP" ]; then
+          echo "Error: EC2_PUBLIC_IP is not set."
+          exit 1
+        fi
         echo "EC2_PUBLIC_IP: $EC2_PUBLIC_IP"
         ssh-keyscan -H $EC2_PUBLIC_IP >> ~/.ssh/known_hosts
-
-        # Ensure the private key is used correctly
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
-
-        # Output the known hosts file for debugging
         cat ~/.ssh/known_hosts
 
 
