cicd_pipeline.yml

diff --git a/.github/workflows/cicd_pipeline.yml b/.github/workflows/cicd_pipeline.yml
--- a/.github/workflows/cicd_pipeline.yml
+++ b/.github/workflows/cicd_pipeline.yml
@@ -33,16 +33,20 @@ jobs:
     - name: Terraform Apply
       run: terraform apply -auto-approve
 
-    - name: Terraform Output Debug
-      run: terraform output
-
-   # Fetch the EC2 Public IP and set it as a GitHub environment variable
-    - name: Fetch EC2 Public IP
-      id: fetch_ip
+    - name: Debug Terraform Output
       run: |
-        EC2_PUBLIC_IP=$(terraform output -raw instance_public_ip)
-        echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
+          if terraform output -raw instance_public_ip; then
+            echo "EC2 Public IP is: $(terraform output -raw instance_public_ip)"
+            EC2_PUBLIC_IP=$(terraform output -raw instance_public_ip)
+            echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
+          else
+            echo "Terraform output not available or EC2 instance creation failed."
+            exit 1
+          fi
 
+    - name: Debug EC2_PUBLIC_IP
+      run: |
+          echo "EC2_PUBLIC_IP is: ${{ env.EC2_PUBLIC_IP }}"
     
     # Step 6: Install Ansible on the GitHub Actions runner
     - name: Install Ansible
